import { buildThresholdConfig, resolveLoadProfile } from "./profiles.js";
import { normalizeInteger } from "./utils.js";

function normalizeAuth(auth = {}) {
  const type = auth.type || "none";

  if (type === "basic") {
    return {
      type,
      username: auth.username || "",
      password: auth.password || ""
    };
  }

  if (type === "api_key") {
    return {
      type,
      location: auth.location === "query" ? "query" : "header",
      keyName: auth.keyName || "x-api-key",
      value: auth.value || ""
    };
  }

  if (type === "token") {
    return {
      type,
      headerName: auth.headerName || "X-Auth-Token",
      token: auth.token || ""
    };
  }

  if (type === "bearer") {
    return {
      type,
      token: auth.token || ""
    };
  }

  if (type === "oauth_existing") {
    return {
      type,
      existingToken: auth.existingToken || auth.token || ""
    };
  }

  if (type === "oauth_client_credentials") {
    return {
      type,
      tokenUrl: auth.tokenUrl || "",
      clientId: auth.clientId || "",
      clientSecret: auth.clientSecret || "",
      scope: auth.scope || ""
    };
  }

  if (type === "oauth_password") {
    return {
      type,
      tokenUrl: auth.tokenUrl || "",
      clientId: auth.clientId || "",
      clientSecret: auth.clientSecret || "",
      username: auth.username || "",
      password: auth.password || "",
      scope: auth.scope || ""
    };
  }

  return { type: "none" };
}

function normalizePayload(payloadType, payload) {
  if (payloadType === "json") {
    if (payload !== null && typeof payload === "object") {
      return payload;
    }
    return {};
  }

  if (payloadType === "text") {
    return typeof payload === "string" ? payload : "";
  }

  return null;
}

function groupDynamicRules(rules = []) {
  const grouped = {
    headers: [],
    queryParams: [],
    payload: []
  };

  for (const rule of rules) {
    if (!rule || !grouped[rule.area] || rule.mode === "static") {
      continue;
    }

    grouped[rule.area].push({
      area: rule.area,
      path: rule.path || "$",
      strategy: rule.strategy || "random_string",
      options: rule.options || {}
    });
  }

  return grouped;
}

function normalizeAssertions(assertions = {}) {
  return {
    statusCode: normalizeInteger(assertions.statusCode, 200),
    bodyContains: Array.isArray(assertions.bodyContains)
      ? assertions.bodyContains.filter((item) => String(item || "").trim())
      : [],
    bodyRegex: Array.isArray(assertions.bodyRegex)
      ? assertions.bodyRegex.filter((item) => String(item || "").trim())
      : []
  };
}

function normalizeSpec(spec = {}) {
  const request = spec.request || {};
  const payloadType = request.payloadType || "none";

  return {
    meta: {
      name: spec.meta?.name || "generated-k6-test",
      description: spec.meta?.description || "",
      generatedAt: new Date().toISOString()
    },
    baseUrl: spec.baseUrl || "https://example.com",
    request: {
      path: request.path || "/",
      method: request.method || "GET",
      headers: request.headers || {},
      queryParams: request.queryParams || {},
      payloadType,
      payload: normalizePayload(payloadType, request.payload)
    },
    auth: normalizeAuth(spec.auth),
    assertions: normalizeAssertions(spec.assertions),
    dynamicRules: groupDynamicRules(spec.dynamicRules),
    options: {
      scenarios: {
        generated_endpoint: resolveLoadProfile(spec.loadProfile || {})
      },
      thresholds: buildThresholdConfig(spec.thresholds || {})
    }
  };
}

function generateConfigFile(config) {
  return [
    "// Auto-generated by k6-script-generator.",
    "",
    "export const config = " + JSON.stringify(config, null, 2) + ";",
    ""
  ].join("\n");
}

function hasDynamicRules(config) {
  return Object.values(config.dynamicRules || {}).some((rules) => Array.isArray(rules) && rules.length > 0);
}

function needsOAuthHelper(config) {
  return config.auth.type === "oauth_client_credentials" || config.auth.type === "oauth_password";
}

function needsEncodingImport(config) {
  return config.auth.type === "basic";
}

function tokenizePath(path) {
  if (!path || path === "$") {
    return [];
  }

  const tokens = [];
  const matcher = /([^.[\]]+)|\[(\d+)\]/g;
  let match;

  while ((match = matcher.exec(path)) !== null) {
    if (match[1] !== undefined) {
      tokens.push(match[1]);
    } else {
      tokens.push(Number(match[2]));
    }
  }

  return tokens;
}

function buildPathExpression(rootExpression, path) {
  const tokens = tokenizePath(path);
  if (!tokens.length) {
    return rootExpression;
  }

  return tokens.reduce((expression, token) => {
    if (typeof token === "number") {
      return `${expression}[${token}]`;
    }
    return `${expression}[${JSON.stringify(token)}]`;
  }, rootExpression);
}

function collectUsedStrategies(config) {
  const strategies = new Set();

  Object.values(config.dynamicRules || {}).forEach((rules) => {
    (rules || []).forEach((rule) => {
      strategies.add(rule.strategy);
    });
  });

  return strategies;
}

function generateDynamicExpression(rule) {
  const options = rule.options || {};

  if (rule.strategy === "uuid") {
    return "uuidv4()";
  }
  if (rule.strategy === "iso_datetime") {
    return "new Date().toISOString()";
  }
  if (rule.strategy === "epoch_seconds") {
    return "Math.floor(Date.now() / 1000)";
  }
  if (rule.strategy === "epoch_millis") {
    return "Date.now()";
  }
  if (rule.strategy === "random_string") {
    return `randomString(${Math.max(4, Number(options.length || 10))})`;
  }
  if (rule.strategy === "random_digits") {
    return `randomDigits(${Math.max(1, Number(options.length || 6))})`;
  }
  if (rule.strategy === "integer_digits") {
    return `Number(randomDigits(${Math.max(1, Number(options.digits || 6))}))`;
  }
  if (rule.strategy === "integer_range") {
    return `randomInt(${Number(options.min || 0)}, ${Number(options.max || 100)})`;
  }
  if (rule.strategy === "float_range") {
    return `randomFloat(${Number(options.min || 0)}, ${Number(options.max || 1)})`;
  }
  if (rule.strategy === "boolean_flip") {
    return "Math.random() >= 0.5";
  }
  if (rule.strategy === "email") {
    return `randomEmail(${JSON.stringify(options.domain || "example.test")})`;
  }
  if (rule.strategy === "lorem_text") {
    return `randomText(${Math.max(10, Number(options.minLength || 40))})`;
  }
  if (rule.strategy === "pattern") {
    return `patternValue(${JSON.stringify(options.segments || [])})`;
  }

  return "undefined";
}

function generateDynamicHelperFile(config) {
  const strategies = collectUsedStrategies(config);
  const lines = [];

  lines.push("function clone(value) {");
  lines.push("  if (value === null || typeof value !== \"object\") {");
  lines.push("    return value;");
  lines.push("  }");
  lines.push("  return JSON.parse(JSON.stringify(value));");
  lines.push("}");
  lines.push("");

  if (
    strategies.has("random_string") ||
    strategies.has("random_digits") ||
    strategies.has("integer_digits") ||
    strategies.has("uuid") ||
    strategies.has("email") ||
    strategies.has("lorem_text") ||
    strategies.has("pattern")
  ) {
    lines.push("function randomFromCharset(length, charset) {");
    lines.push("  var output = \"\";");
    lines.push("  for (var i = 0; i < length; i += 1) {");
    lines.push("    var index = Math.floor(Math.random() * charset.length);");
    lines.push("    output += charset.charAt(index);");
    lines.push("  }");
    lines.push("  return output;");
    lines.push("}");
    lines.push("");
  }

  if (strategies.has("random_string")) {
    lines.push("function randomString(length) {");
    lines.push("  return randomFromCharset(length, \"abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789\");");
    lines.push("}");
    lines.push("");
  }

  if (strategies.has("random_digits") || strategies.has("integer_digits") || strategies.has("email") || strategies.has("pattern")) {
    lines.push("function randomDigits(length) {");
    lines.push("  return randomFromCharset(length, \"0123456789\");");
    lines.push("}");
    lines.push("");
  }

  if (strategies.has("integer_range")) {
    lines.push("function randomInt(min, max) {");
    lines.push("  var low = Math.min(min, max);");
    lines.push("  var high = Math.max(min, max);");
    lines.push("  return Math.floor(Math.random() * (high - low + 1)) + low;");
    lines.push("}");
    lines.push("");
  }

  if (strategies.has("float_range")) {
    lines.push("function randomFloat(min, max) {");
    lines.push("  var low = Math.min(min, max);");
    lines.push("  var high = Math.max(min, max);");
    lines.push("  return Number((Math.random() * (high - low) + low).toFixed(3));");
    lines.push("}");
    lines.push("");
  }

  if (strategies.has("uuid")) {
    lines.push("function uuidv4() {");
    lines.push("  return \"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx\".replace(/[xy]/g, function (char) {");
    lines.push("    var random = Math.floor(Math.random() * 16);");
    lines.push("    var value = char === \"x\" ? random : (random & 0x3) | 0x8;");
    lines.push("    return value.toString(16);");
    lines.push("  });");
    lines.push("}");
    lines.push("");
  }

  if (strategies.has("email")) {
    lines.push("function randomEmail(domain) {");
    lines.push("  return \"user_\" + randomDigits(6) + \"@\" + domain;");
    lines.push("}");
    lines.push("");
  }

  if (strategies.has("lorem_text")) {
    lines.push("function randomText(minLength) {");
    lines.push("  var text = \"\";");
    lines.push("  while (text.length < minLength) {");
    lines.push("    text += randomFromCharset(6, \"abcdefghijklmnopqrstuvwxyz\") + \" \";");
    lines.push("  }");
    lines.push("  return text.trim();");
    lines.push("}");
    lines.push("");
  }

  if (strategies.has("pattern")) {
    lines.push("function patternValue(segments) {");
    lines.push("  var output = \"\";");
    lines.push("  for (var i = 0; i < segments.length; i += 1) {");
    lines.push("    var segment = segments[i];");
    lines.push("    var count = Math.max(1, Number(segment.count || 1));");
    lines.push("    if (segment.type === \"upper\") {");
    lines.push("      output += randomFromCharset(count, \"ABCDEFGHIJKLMNOPQRSTUVWXYZ\");");
    lines.push("    } else if (segment.type === \"lower\") {");
    lines.push("      output += randomFromCharset(count, \"abcdefghijklmnopqrstuvwxyz\");");
    lines.push("    } else if (segment.type === \"digit\") {");
    lines.push("      output += randomDigits(count);");
    lines.push("    } else {");
    lines.push("      output += String(segment.value || \"X\").repeat(count);");
    lines.push("    }");
    lines.push("  }");
    lines.push("  return output;");
    lines.push("}");
    lines.push("");
  }

  lines.push("export function applyDynamicData(request) {");
  lines.push("  var requestData = {");
  lines.push("    headers: clone(request.headers || {}),");
  lines.push("    queryParams: clone(request.queryParams || {}),");
  lines.push("    payload: clone(request.payload)");
  lines.push("  };");
  lines.push("");

  for (const [area, rules] of Object.entries(config.dynamicRules || {})) {
    const rootExpression =
      area === "headers"
        ? "requestData.headers"
        : area === "queryParams"
          ? "requestData.queryParams"
          : "requestData.payload";

    for (const rule of rules) {
      const targetExpression = buildPathExpression(rootExpression, rule.path);
      lines.push(`  ${targetExpression} = ${generateDynamicExpression(rule)};`);
    }
  }

  lines.push("");
  lines.push("  return requestData;");
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

function generateOAuthHelperFile() {
  return [
    "import http from \"k6/http\";",
    "import { fail } from \"k6\";",
    "",
    "function formEncode(data) {",
    "  return Object.entries(data)",
    "    .filter(function (entry) {",
    "      return entry[1] !== undefined && entry[1] !== null && entry[1] !== \"\";",
    "    })",
    "    .map(function (entry) {",
    "      return encodeURIComponent(entry[0]) + \"=\" + encodeURIComponent(String(entry[1]));",
    "    })",
    "    .join(\"&\");",
    "}",
    "",
    "export function getAccessToken(auth) {",
    "  if (!auth.tokenUrl) {",
    "    fail(\"OAuth tokenUrl is required\");",
    "  }",
    "",
    "  var payload = auth.type === \"oauth_client_credentials\"",
    "    ? {",
    "        grant_type: \"client_credentials\",",
    "        client_id: auth.clientId,",
    "        client_secret: auth.clientSecret,",
    "        scope: auth.scope || undefined",
    "      }",
    "    : {",
    "        grant_type: \"password\",",
    "        client_id: auth.clientId,",
    "        client_secret: auth.clientSecret,",
    "        username: auth.username || undefined,",
    "        password: auth.password || undefined,",
    "        scope: auth.scope || undefined",
    "      };",
    "",
    "  var response = http.post(auth.tokenUrl, formEncode(payload), {",
    "    headers: { \"Content-Type\": \"application/x-www-form-urlencoded\" }",
    "  });",
    "",
    "  if (response.status >= 400) {",
    "    fail(\"OAuth token request failed with status \" + response.status);",
    "  }",
    "",
    "  var body = {};",
    "  try {",
    "    body = response.json();",
    "  } catch (error) {",
    "    fail(\"OAuth token response is not valid JSON\");",
    "  }",
    "",
    "  var token = body.access_token || body.id_token || \"\";",
    "  if (!token) {",
    "    fail(\"OAuth response does not include access_token\");",
    "  }",
    "",
    "  return token;",
    "}",
    ""
  ].join("\n");
}

function collectValidRegexPatterns(assertions = {}) {
  return (assertions.bodyRegex || []).filter((pattern) => {
    try {
      new RegExp(pattern);
      return true;
    } catch {
      return false;
    }
  });
}

function generateScriptFile(config) {
  const dynamic = hasDynamicRules(config);
  const oauthHelper = needsOAuthHelper(config);
  const encodingImport = needsEncodingImport(config);
  const authType = config.auth.type;
  const validRegexPatterns = collectValidRegexPatterns(config.assertions);
  const lines = [];

  lines.push("import http from \"k6/http\";");
  lines.push("import { check } from \"k6\";");
  if (encodingImport) {
    lines.push("import encoding from \"k6/encoding\";");
  }
  if (oauthHelper) {
    lines.push("import { getAccessToken } from \"./auth.js\";");
  }
  if (dynamic) {
    lines.push("import { applyDynamicData } from \"./data-helper.js\";");
  }
  lines.push("import { config } from \"./config.js\";");
  lines.push("");
  lines.push("export const options = config.options;");
  lines.push("");

  validRegexPatterns.forEach((pattern, index) => {
    lines.push(`const bodyRegex${index} = new RegExp(${JSON.stringify(pattern)});`);
  });
  if (validRegexPatterns.length) {
    lines.push("");
  }

  lines.push("const responseChecks = {");
  lines.push(`  ${JSON.stringify(`status is ${config.assertions.statusCode}`)}: (response) => response.status === ${config.assertions.statusCode},`);
  (config.assertions.bodyContains || []).forEach((expected) => {
    lines.push(
      `  ${JSON.stringify(`body contains \"${expected}\"`)}: (response) => typeof response.body === \"string\" && response.body.includes(${JSON.stringify(expected)}),`
    );
  });
  validRegexPatterns.forEach((pattern, index) => {
    lines.push(
      `  ${JSON.stringify(`body matches /${pattern}/`)}: (response) => typeof response.body === \"string\" && bodyRegex${index}.test(response.body),`
    );
  });
  lines.push("};");
  lines.push("");

  if (oauthHelper) {
    lines.push("export function setup() {");
    lines.push("  return getAccessToken(config.auth);");
    lines.push("}");
    lines.push("");
  }

  lines.push(`export default function${oauthHelper ? "(accessToken)" : "()"} {`);
  if (dynamic) {
    lines.push("  const request = { ...config.request, ...applyDynamicData(config.request) };");
  } else {
    lines.push("  const request = config.request;");
  }
  lines.push("");
  lines.push("  const headers = { ...(request.headers || {}) };");
  lines.push("  const queryParams = { ...(request.queryParams || {}) };");
  lines.push("");

  if (authType === "basic") {
    lines.push("  const credentials = `${config.auth.username || \"\"}:${config.auth.password || \"\"}`;");
    lines.push("  headers.Authorization = `Basic ${encoding.b64encode(credentials)}`;");
    lines.push("");
  } else if (authType === "bearer") {
    lines.push("  headers.Authorization = `Bearer ${config.auth.token || \"\"}`;");
    lines.push("");
  } else if (authType === "token") {
    lines.push("  headers[config.auth.headerName || \"X-Auth-Token\"] = config.auth.token || \"\";");
    lines.push("");
  } else if (authType === "api_key") {
    lines.push("  if (config.auth.location === \"query\") {");
    lines.push("    queryParams[config.auth.keyName || \"api_key\"] = config.auth.value || \"\";");
    lines.push("  } else {");
    lines.push("    headers[config.auth.keyName || \"x-api-key\"] = config.auth.value || \"\";");
    lines.push("  }");
    lines.push("");
  } else if (authType === "oauth_existing") {
    lines.push("  headers.Authorization = `Bearer ${config.auth.existingToken || \"\"}`;");
    lines.push("");
  } else if (oauthHelper) {
    lines.push("  headers.Authorization = `Bearer ${accessToken || \"\"}`;");
    lines.push("");
  }

  lines.push("  let body = null;");
  lines.push("  if (request.payloadType === \"json\") {");
  lines.push("    headers[\"Content-Type\"] = headers[\"Content-Type\"] || \"application/json\";");
  lines.push("    body = JSON.stringify(request.payload || {});");
  lines.push("  } else if (request.payloadType === \"text\") {");
  lines.push("    body = typeof request.payload === \"string\" ? request.payload : String(request.payload || \"\");");
  lines.push("  }");
  lines.push("");
  lines.push("  const path = String(request.path || \"/\");");
  lines.push("  const normalizedPath = path.startsWith(\"/\") ? path : `/${path}`;");
  lines.push("  const queryString = Object.entries(queryParams)");
  lines.push("    .filter(([, value]) => value !== undefined && value !== null && value !== \"\")");
  lines.push("    .map(([key, value]) => `${encodeURIComponent(key)}=${encodeURIComponent(String(value))}`)");
  lines.push("    .join(\"&\");");
  lines.push("  const baseUrl = String(config.baseUrl || \"\").replace(/\\/+$/, \"\");");
  lines.push("  const url = queryString ? `${baseUrl}${normalizedPath}?${queryString}` : `${baseUrl}${normalizedPath}`;");
  lines.push("");
  lines.push("  const response = http.request(request.method, url, body, { headers });");
  lines.push("  check(response, responseChecks);");
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

function generateOutputReadme(config, files) {
  const fileNames = Object.keys(files);

  return [
    `# Generated k6 Script: ${config.meta.name}`,
    "",
    "## Files",
    ...fileNames.map((fileName) => `- \`${fileName}\``),
    "",
    "## Run",
    "```bash",
    "k6 run script.js",
    "```",
    ""
  ].join("\n");
}

export function generateProjectFiles(spec) {
  const config = normalizeSpec(spec);
  const files = {
    "config.js": generateConfigFile(config),
    "script.js": generateScriptFile(config)
  };

  if (needsOAuthHelper(config)) {
    files["auth.js"] = generateOAuthHelperFile();
  }

  if (hasDynamicRules(config)) {
    files["data-helper.js"] = generateDynamicHelperFile(config);
  }

  files["README.md"] = generateOutputReadme(config, files);
  return files;
}
